title: Ontario Model United Nations
description: >
  Ontario Model United Nations is a student-run Model United Nations simulation held at Upper Canada College. On the OMUN website, you can discover what committees are available, general conference information, and register as a delegate or school!
baseurl: ""
url: "http://omun.ca"
docurl: "/docs"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [vendor]

# Collections
collections:
  committees:
    output: true
    layout: committee
  docs:
    output: true
    layout: doc
