title: Ontario Model United Nations
email: omun@ucc.on.ca
description: >
  Ontario Model United Nations is a student-run Model United Nations simulation held at Upper Canada College. On the OMUN website, you can discover what committees are available, general conference information, and register as a delegate or school!
baseurl: "/omun"
url: "http://matthewwang.me"
docurl: "/omun/docs"

# Build settings
markdown: kramdown
exclude: [vendor]

# Collections
collections:
  committees:
    output: true
    layout: committee
  docs:
    output: true
    layout: doc
  reg:
    output: true
